# Generated by Django 4.2 on 2023-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diver',
            name='backstory',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='diver',
            name='job',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='diver',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diver',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diver',
            name='race',
            field=models.CharField(default='', max_length=75),
        ),
    ]
