# Generated by Django 4.2 on 2023-05-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_diver_backstory_diver_job_diver_level_diver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diver',
            name='job',
            field=models.CharField(choices=[], default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='diver',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
