# Generated by Django 4.2 on 2023-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_diver_job_alter_diver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diver',
            name='job',
            field=models.CharField(default='', max_length=75),
        ),
    ]
