# Generated by Django 4.2 on 2023-05-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_diver_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diver',
            name='user',
        ),
    ]
