# Generated by Django 4.2 on 2023-05-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_diver_items_item_description_alter_diver_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='diver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.diver'),
        ),
        migrations.AlterField(
            model_name='diver',
            name='job',
            field=models.CharField(max_length=20),
        ),
    ]
