# Generated by Django 4.2 on 2023-05-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_item_diver_alter_diver_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='diver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.diver'),
        ),
    ]
